version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
#    volumes:
#      - /data/postgres:/data/postgres
    env_file:
      - docker.env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
#    volumes:
#      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    depends_on:
      - postgres

  redis:
    container_name: redis
    image: "redis:alpine"
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/data/redis

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis